{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullname" . }}-main
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helpers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      {{- if .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      {{- end }}
      initContainers:
        - name: dependencies-listener
          image: '{{ .Values.backend.busybox.image.repository | default "busybox" }}:{{ .Values.backend.busybox.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.backend.busybox.image.pullPolicy | default "IfNotPresent" }}
          command:
            - sh
            - -ec
            - |
              for i in $(seq 1 200); do
                nc -z -v -w3 {{ include "helpers.extractHostPort" .Values.mysql.url }} && \
                nc -z -v -w3 {{ include "helpers.extractHostPort" .Values.redis.url }} && \
                nc -z -v -w3 {{ include "helpers.extractHostPort" .Values.milvus.url }} && \
                sleep 30 && exit 0 || sleep 3
              done
              exit 1
      containers:
        - name: main
          env:
            - name: SERVICE_OPTS
              value: '-Dspring.config.location=classpath:/application.yml,/home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/config/application-online.yml -Dspring.profiles.active=online'
            - name: SERVER_PORT
              value: {{ default "8080" .Values.backend.container.server.port | quote }}
            - name: MANAGEMENT_PORT
              value: {{ default "8081" .Values.backend.container.management.port | quote }}
            {{- if .Values.backend.debug.jpda.enabled }}
            - name: JPDA_ENABLE
              value: 'true'
            - name: JPDA_PORT
              value: {{ default "5005" .Values.backend.debug.jpda.port | quote }}
            {{- end }}
          {{- if .Values.backend.securityContext }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          {{- end }}
          image: '{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ default 8080 .Values.backend.container.server.port }}
              protocol: TCP
            - name: management
              containerPort: {{ default 8081 .Values.backend.container.management.port }}
              protocol: TCP
            {{- if .Values.backend.debug.jpda.enabled }}
            - name: jpda
              containerPort: {{ default 5005 .Values.backend.debug.jpda.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /public/actuator/health/liveness
              port: management
            initialDelaySeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /public/actuator/health/readiness
              port: management
            initialDelaySeconds: 30
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-private
              mountPath: /home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/config
            - name: config-runtime
              mountPath: /home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/config.run
            - name: storage
              mountPath: /home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/logs
              subPath: logs
            - name: storage
              mountPath: /home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/data
              subPath: data
        {{- if (index .Values "grafana-loki" "enabled") }}
        - name: promtail
          image: '{{ .Values.backend.promtail.image.repository | default "grafana/promtail" }}:{{ .Values.backend.promtail.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.backend.promtail.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: promtail-positions
              mountPath: /run/promtail
            - name: storage
              mountPath: /home/{{ .Values.backend.systemAccount }}/{{ include "helpers.name" . }}/logs
              subPath: logs
        {{- end }}
      volumes:
        - name: config-private
          secret:
            secretName: {{ include "helpers.fullname" . }}-spring-properties
            items:
              - key: application-online.yml
                path: application-online.yml
        - name: config-runtime
          configMap:
            name: {{ include "helpers.fullname" . }}-runtime-configuration
            items:
              - key: application-runtime.properties
                path: application-runtime.properties
        {{- if .Values.backend.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "helpers.fullname" . }}-pvc
        {{- else }}
        - name: storage
          emptyDir: {}
        {{- end }}
        {{- if (index .Values "grafana-loki" "enabled") }}
        - name: promtail-config
          configMap:
            name: {{ include "helpers.fullname" . }}-promtail-configuration
            items:
              - key: promtail.yaml
                path: promtail.yaml
        - name: promtail-positions
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}